name: Compilar OPL 1907 (Unificado)

on:
  workflow_dispatch:
  push:
    paths:
      - 'patch_opl_1907.py'
      - '.github/workflows/build_opl_1907.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git python3 curl wget bash py3-yaml

      - name: Checkout custom scripts
        uses: actions/checkout@v4
        with:
          path: custom_repo

      - name: Clone OPL repository
        run: |
          git clone https://github.com/ps2homebrew/Open-PS2-Loader.git
          cd Open-PS2-Loader
          git checkout 48e2d132532088aaba8e82c7149e4c4164d0ac64
          git submodule update --init --recursive

      - name: Apply Unified Menu Patches
        run: |
          cp custom_repo/patch_opl_1907.py Open-PS2-Loader/
          cd Open-PS2-Loader
          python3 patch_opl_1907.py

      - name: Compile OPL
        run: |
          cd Open-PS2-Loader
          make clean
          make download_lng
          make -j$(nproc)

      - name: Upload OPL ELF
        uses: actions/upload-artifact@v4
        with:
          name: OPNPS2LD-1907-Unified
          path: Open-PS2-Loader/OPNPS2LD.ELF
          if-no-files-found: error
